DELETE http://localhost:3003/api/blogs/63d3ea2e63061856d3598cde
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRpbSIsImlkIjoiNjNkM2E2NjE5YWZhYjk0NjNlNDk5N2ZmIiwiaWF0IjoxNjc0ODMyMzI3fQ.G-KB8oLeg52TIpNoz8_TVHCgXeZeGWPtclZgsmjfWGc
